### PR TITLE
Avoid Trademark and Copyright Enforcement Action

### PR DESCRIPTION
**Pull request by bone-baboon**
To avoid trademark and copyright enforcement action it is probably a good idea to remove the files in the Questionable Files section below.

# Character Trademark and Copyright

Fictional characters can be protected by copyright and trademark.
This is an explanation that uses Disney characters.
<https://info.legalzoom.com/article/legal-use-disney-characters> 

# Questionable Files

Some of the files used by cowsay's -f option appear to be
questionable. I looked at all the files in the cows directory and the
following files were the ones I identified as questionable. All of the
following charters are likely trademarked and copyrighted (however I
have not verified that).

* beavis.zen.cow 
  * <https://en.wikipedia.org/wiki/Beavis_and_Butt-Head>
  * Uses trademarked character name and character

* bud-frogs.cow 
  * <https://en.wikipedia.org/wiki/Budweiser>
  * <https://en.wikipedia.org/wiki/Budweiser_Frogs>
  * Uses trademark and characters

* cheese.cow 
  * <https://en.wikipedia.org/wiki/Milk_%26_Cheese>
  * Uses trademark character name and character

* ghostbusters.cow 
  * <https://en.wikipedia.org/wiki/Ghostbusters>
  * Uses trademark and no ghost logo

* hellokitty.cow 
  * <https://en.wikipedia.org/wiki/Hello_Kitty>
  * Uses trademark and character

* luke-koala.cow 
  * <https://en.wikipedia.org/wiki/Luke_Skywalker>
  * Uses trademarked character name

* milk.cow 
  * <https://en.wikipedia.org/wiki/Milk_%26_Cheese>
  * Uses trademark character name and character

* ren.cow 
  * <https://en.wikipedia.org/wiki/The_Ren_%26_Stimpy_Show>
  * Uses trademark character name and character

* stimpy.cow 
  * <https://en.wikipedia.org/wiki/The_Ren_%26_Stimpy_Show>
  * Uses trademark character name and character

* telebears.cow 
  * <https://brand.berkeley.edu/uncategorized/telebears/>
  * Uses trademark

* vader-koala.cow 
  * <https://en.wikipedia.org/wiki/Darth_Vader>
  * Uses trademark character name

These two may be fair use:

* moofasa.cow 
  * <https://en.wikipedia.org/wiki/Mufasa#Mufasa>

* vader.cow 
  * <https://en.wikipedia.org/wiki/Darth_Vader>

### CODE REVIEW

**Comment by apjanke** [comment]
Hi there, bone-baboon. Thanks for your submission!

IANAL, but I'm not sure there's a significant problem here.

I don't think copyright is at issue here: characters themselves can't be copyrighted; only particular works or realizations of them. In this case, I'm pretty sure the cowfiles are the works, and the copyright is held by the creators of the cowfiles, not the owners of the characters. Cowsay hasn't done stringent tracking of copyright and licensing, but the fact that these were created as cowfiles, and the only use of cowfiles is to go in to cows, is a pretty strong indication that the authors intended to grant license for such use of these files.

Trademark is another issue. Given that this is a noncommercial work, and these are essentially little funny doodles of the characters, there's a good chance that this falls under "fair use", as a parody, transformative work, or insufficiently-convincing likeness. And they're just little doodles and not being sold, so if there is infringement going on here, I'm thinking it's "de minimus".

In any case, I think it's highly unlikely that we'd actually run in to legal trouble for this use, even if there is some degree of infringement.

If there are any actual IP lawyers, relevant IP owners, or distributions who redistribute cowsay who would like to weigh in on this, I'd definitely like to hear what you have to say.

But in the mean time, I don't think I'm going to do anything about this, and am going to pass on this PR. I'll leave it open for a few days, though, for additional discussion and comment.

**Comment by bone-baboon** [comment]
@apjanke

During the June 25 2021 Free Software Directory meeting held by the
Free Software Foundation I brought up the issue of these questionable
files in the cowsay repository.  The suggestion I received in that
meeting was was to find a cowsay repository that did not have the
questionable files and edit the Free Software Directory cowsay listing
to link to that repository of cowsay.

Not having found a cowsay repository without these files I decided to
submit pull requests to this repository as well as
<https://github.com/cowsay-org/cowsay>.

**Comment by bone-baboon** [comment]
Guix <https://guix.gnu.org/> packages cowsay using the source code in
this repository.  On Guix's development mailing list guix-devel
<https://lists.gnu.org/mailman/listinfo/guix-devel> there was this
response to the questionable files in the cowsay repository:
<https://lists.gnu.org/archive/html/guix-devel/2021-07/msg00095.html>

**Comment by tnalpgge** [comment]
@bone-baboon Please read [CONTRIBUTING.md](/tnalpgge/rank-amateur-cowsay/tree/master/CONTRIBUTING.md) in this repository as [README.md](/tnalpgge/rank-amateur-cowsay/tree/master/README.md) recommended.  By responding I am violating my own standard here, but I think it is necessary.

If Guix wishes to distribute cowsay, and they reasonably fear legal action over ASCII art that has been wandering the internet   for 20+ years, then they can find or create a fork or a redistribution or a package or an installation method that does not include the cowfiles they find objectionable.  I don't object and I couldn't stop them anyway.

I would like to think that major IP holders would have gotten around to suing me out of house and home by now if they thought their cases would benefit them.  But they haven't.  Maybe it's as simple as money and reputation: there's far more reputation for them to lose than money to gain.  I've never made money from cowsay, I've never tried, and I find it exceedingly unlikely that I ever will.

**Comment by bone-baboon** [comment]
@tnalpgge thank you for publishing cowsay under a free libre open source license.

cowsay is fun and makes people smile. :)

**Pull request closed without merging**
