### PR TITLE
add additional cowfiles from FreeBSD ports collection

### PR DESCRIPTION
**Pull request by lifanov**

### CODE REVIEW

**Comment by strugee** [comment]
https://github.com/tnalpgge/rank-amateur-cowsay/blob/master/CONTRIBUTING.md

> The repository at https://github.com/tnalpgge/rank-amateur-cowsay.git is available for forking to any interested parties. **Issues and pull requests on that repository will be ignored.**

(Emphasis mine)

**Comment by strugee** [comment]
Just as an FYI :)

**Comment by lifanov** [comment]
Ohh okay. I didn't read CONTRIBUTING that closely. If this is rejected, I'll just rebase port on my fork.

**Comment by DominoTree** [comment]
Are there any licensing issues with including stuff from FreeBSD ports (BSD-licensed) in a product licensed under GPLv3?  Shouldn't there be a separate license for those cowfiles?

**Comment by lifanov** [comment]
Hi! You may be right, if only that the three files don't contain copyright notices.
I will close this for now until I can think of a way to "fix" this.

**Pull request closed without merging**
